# Generated by Django 4.2.4 on 2023-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_added', models.DateField(blank=True, null=True, verbose_name='Date added')),
                ('ready_to', models.BooleanField(default=False, verbose_name='Ready')),
            ],
        ),
    ]
